apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-nov6-newapp-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/pipelines/docker-build-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/tasks/buildah-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/tasks/update-deployment.yaml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/tasks/show-sbom-rhdh.yaml"
    pipelinesascode.tekton.dev/task-5: "https://raw.githubusercontent.com/redhat-ai-dev/rhdh-pipelines/release-v0.9.x/pac/tasks/summary.yaml"
  labels:
    argocd/app-name: test-nov6-newapp
    janus-idp.io/tekton: test-nov6-newapp
    backstage.io/kubernetes-id: test-nov6-newapp
    backstage.io/kubernetes-namespace: rhdh-app
    app.kubernetes.io/part-of: test-nov6-newapp
spec:
  params:
    - name: dockerfile
      value: Containerfile
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/jdubrick-ai/test-app:{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: event-type
      value: '{{event_type}}'
    - name: gitops-auth-secret-name
      value: gitops-auth-secret
  pipelineRef:
    name: docker-build-ai-rhdh
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
